export { default as Post } from '../../pages/posts/[id]'
export { default as Project } from '../../pages/projects/[id]'
export { default as Albu } from '../../pages/Album/[id]'
export { default as Product } from '../../pages/products/[id]'
export { default as Withpag } from '../../pages/withpage/[id]'
export { default as Recipe } from '../../pages/recipes/[id]'
export { default as Pag } from '../../pages/page/[id]'
