import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Img from 'react-cool-img'

import {
  loginWithGithub,
  fetchPosts,
  makeAdmin,
  isAdmin
} from 'firebase/client'
import { useEffect, useState } from 'react'
import { useUser } from '@/hooks/useUser'

export default function Home () {
  const [user, admin] = useUser()

  const [posts, setPosts] = useState([])
  const [email, setEmail] = useState('')

  // useEffect(() => {
  //   fetchPosts().then(setPosts)
  // }, [])

  const login = () => {
    loginWithGithub()
      .then(user => {
        setUser(user)
      })
      .catch(err => {
        console.log(err)
      })
  }

  const handeAdminSubmit = e => {
    e.preventDefault()
    // console.log('handle submit', email)
    makeAdmin(email)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to my <a href='https://nextjs.org'>Blog!</a>
        </h1>
        {/* {admin &&
          posts &&
          posts.map((post, i) => {
            return <p key={i}>{post.content}</p>
          })} */}
        {user === null ? (
          <button onClick={login}>Login with GitHub</button>
        ) : (
          <div>
            {user.username}
            <Img src={user.avatar} alt='avatar' width='125' height='125' />
          </div>
        )}
      </main>

      <form onSubmit={handeAdminSubmit}>
        <label>Create admin</label>
        <input
          type='text'
          value={email}
          onChange={e => {
            setEmail(e.target.value)
          }}
        />
        <button type='submit'>Make admin</button>
      </form>

      {/* <button
        onClick={() => {
          isAdmin(setAdmin)
          console.log(admin)
        }}
      >
        Is admin?
      </button> */}

      <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
